### ISSUE TITLE
Project Peer Review: Contact Page

### ISSUE THREAD

**Issue by yxia1** [mollyhennessy/WebTechProject#2]

**Comment by yxia1** [comment]
This is a very small issue. I think the page will look more balanced if the default size of the textarea for the comment section is slightly bigger. You can try the following code.

```
  <textarea
          name="comments"
          id="comments"
          cols="50"
          rows="6"
          placeholder="Enter your comments here..."
        ></textarea>
```

**Comment by mollyhennessy** [comment]
I like your idea! thanks
