### ISSUE TITLE
Project Peer Review: Homepage Content

### ISSUE THREAD

**Issue by yxia1** [mollyhennessy/WebTechProject#4]
I think the homepage needs a bit more content. To make the page looks fuller, you can enlarge the embedded youtube video and choose to make it autoplay with sound off so that when the user first land on the page, they can watch the video. 

```
  <iframe
      width="560"
      height="315"
      src="https://www.youtube.com/embed/LRb0l3xA1U0?mute=1&autoplay=1"
      title="YouTube video player"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      allowfullscreen
    ></iframe>
```

In addition, I think it is a good place to list all the honors and awards that the team has earned. In general, more content and picture would be better.

**Comment by mollyhennessy** [comment]
this is super helpful thank you
